version: "3"
services:

  proxyserver:
    image: nginx
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./servicemap-conf/img:/ServiceMap/img

#KBSSM ################################################################      
  servicemap:
    image: disitlab/servicemap:v2.1
    volumes:
#      - ./servicemap-conf/ServiceMap.war:/usr/local/tomcat/webapps/ServiceMap.war
#      - ./servicemap-conf/iot.war:/usr/local/tomcat/webapps/iot.war
      - ./servicemap-conf:/root/servicemap
#      - ./servicemap-conf/cacerts:/usr/local/openjdk-8/jre/lib/security/cacerts
      - ./servicemap-iot-conf/logs:/root/iot-log2
      - ./servicemap-iot-conf/:/root/iot-api-config/
      - ./servicemap-conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./servicemap-superservicemap-conf/settings.xml:/usr/local/tomcat/settings.xml
    environment:
      TZ: "Europe/Rome"
      JAVA_OPTS: "-Dcom.sun.net.ssl.checkRevocation=false"
    ports:
      - 8080:8080
    extra_hosts:
      - "www.snap4city.org:192.168.1.82"
    restart: unless-stopped
    depends_on:
      - virtuoso-kb
      - smdb
  virtuoso-kb:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.1
    environment:
      TZ: "Europe/Rome"
      SPARQL_UPDATE: "true"
      VIRT_Parameters_MaxBuffers: 340000
      VIRT_Parameters_MaxDirtyBuffers: 250000
      VIRT_Parameters_ServerThreads: 100
    volumes:
      - ./servicemap-conf:/root/servicemap
      - virtuoso:/data
    ports:
      - "8890:8890"
      - "1111:1111"
    restart: unless-stopped
  solr-kb:
    image: solr:6.6.6
    ports:
     - "8983:8983"
    restart: unless-stopped
    volumes:
      - solr-data:/var/solr
    command:
      - solr-precreate
      - km4c-index

######################################################################      
  smdb:
    image: mariadb
    volumes:
      - smdb:/var/lib/mysql
      - ./database/servicemap.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./database/superservicemap.sql:/docker-entrypoint-initdb.d/2_init.sql
    environment:
      TZ: "Europe/Rome"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'passwordx'
      MYSQL_DATABASE: 'Dashboard'      
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  smdb:
  virtuoso:
  solr-data:
