version: "3"
services:
  proxy:
    image: nginx
    networks:
      default:
        aliases: 
          - dashboard 
    ports:
      - "80:80" 
    volumes:
      - ./nginx-proxy-conf:/etc/nginx/conf.d
    depends_on:
      - dashboard-builder
      - keycloak
      - servicemap
      - personaldata
      - wsserver
      - synoptics
      - iot-discovery
      - iotapp-nr1
      - iotapp-nr2
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

  dashboard-builder:
    image: disitlab/dashboard-builder:v5
    ports:
      - "70:80"
    volumes:
       - ./dashboard-builder-conf:/var/www/html/dashboardSmartCity/conf
       - ./notificator-conf:/var/www/html/notificator/conf
       - ./iot-directory-conf:/var/www/html/iot-directory/conf
       - ./iot-directory-certificate:/var/www/certificate
       - ./iot-directory-log:/var/www/log
       - ./apache-proxy.conf:/etc/apache2/conf-virtualhost/proxy.conf
       - ./processloader-conf/config.php:/var/www/html/processloader/config.php
       - ./processloader-conf/external_service.php:/var/www/html/processloader/external_service.php
       - ./ownership-conf/config.php:/var/www/html/ownership-api/config.php
       - ./ownership-conf/logs:/ownership-logs
       - dashboard-img:/var/www/html/dashboardSmartCity/img
    environment:
      OWN_DB_HOST: "dashboarddb"
      OWN_DB_USER: "user"
      OWN_DB_PWD: "passwordx"
      OWN_SSO_USERINFO_ENDPOINT: "http://dashboard/auth/realms/master/protocol/openid-connect/userinfo"
      OWN_LDAPSERVER: "ldap-server"
      OWN_LDAPBASEDN: "dc=ldap,dc=organization,dc=com"
    depends_on:
      - dashboarddb
      - keycloak 
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  dashboard-backend:
    image: disitlab/dashboard-backend:v0
    volumes:
      - ./dashboard-backend-conf/config.properties:/usr/app/config.properties
    depends_on: 
      - dashboarddb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  dashboard-cron:
    image: disitlab/dashboard-builder:v5
    volumes:
       - ./dashboard-builder-conf:/var/www/html/dashboardSmartCity/conf
       - ./dashboard-cron-conf/crontab:/crontab
    command: /bin/sh -c "crontab /crontab; cron -f"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  personaldata:
    image: disitlab/personaldata:v3.1
#    image: tomcat:9.0.26-jdk8-openjdk-slim
    volumes:
      - ./datamanager-logs:/usr/local/tomcat/logs/datamanager
      - ./datamanager-conf:/datamanager-conf
    environment:
      "spring.profiles.active": "deploy"
      "profiledb.datasource.url": "jdbc:mysql://dashboarddb:3306/profiledb"
      "profiledb.datasource.username": "user"
      "profiledb.datasource.password": "passwordx"
      "spring.openidconnect.userinfo_endpoint": "http://dashboard/auth/"
      "spring.openidconnect.userinfo_endpoint_test": ""
      "spring.ldap.url": "ldap://ldap-server:389"
      "spring.ldap.basicdn": "dc=ldap,dc=organization,dc=com"
      "spring.ldap.managerdn": "cn=admin,dc=ldap,dc=organization,dc=com"
      "spring.ldap.password": "secret"
      "config.kpi.organizationlist": "[\"Organization\"]"
      "config.kpi.dictionary": "http://dashboard/processloader/api/dictionary/"
      "config.kpi.authentication.clientid": "js-kpi-client"
      "config.kpi.defaultsaveon": "ElasticSearch"
      "config.grp.authentication.clientid": "js-grp-client"
      "grpsensors.datasource.url": "http://dashboard/dashboardSmartCity/api/sensors.php"
      "grp.url": "http://dashboard/datamanager/grp/?id=%d"
#     "spring.cache.jcache.config": "classpath:ehcache.xml"
      "kafka.bootstrapAddress": "kafka:9092"
      "kafka.prefixTopic": "kpi-"
      "kafka.sendMessages": "true"
      "elasticsearch.truststorefile": "/datamanager-conf/trust-store.p12"
      "elasticsearch.truststorepass": "snap4ca"
      "elasticsearch.username": "admin"
      "elasticsearch.password": "admin"
      "elasticsearch.clustername": "na"
      "elasticsearch.protocol": "https"
      "elasticsearch.hosts": "opensearch-n1"
      "elasticsearch.port": "9200"
      "elasticsearch.kibanahost": "http://dashboard/kibana"
      "elasticsearch.kibanaDashboardUrl": "http://dashboard/kibana/app/dashboards?security_tenant=global#/view/264dd3d0-23f0-11eb-9e9d-e5f981c2aab7?_a=(filters:!(),query:(language:lucene,query:'deviceName:KPI_ID'))"
      "elasticsearch.indexname": "snap4-kpi"
      #set the same as dashboard-builder and ownership
      "security.encryptor.aes.secretkey": "EncryptionIniKey" 
      "security.encryptor.aes.ivparameter": "IVKeyivKey123456"
      "JAVA_OPTS": "-DlogFileFolder=/usr/local/tomcat/logs"
    ports:
      - 8080:8080
    links:
      - dashboarddb
    depends_on:
      - dashboarddb
      - keycloak 
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  wsserver:
    image: disitlab/websocketserver:v3
    ports:
      - 9000:8000
    volumes:
      - ./dashboard-builder-conf:/websocketserver/conf
    depends_on:
      - dashboarddb
      - keycloak 
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  synoptics:
    image: disitlab/synoptics:v1
    volumes:
      - ./synoptics-conf/config.js:/usr/src/synoptics/new-config.js
      - ./synoptics-conf/v2-config.js:/usr/src/synoptics/v2/new-config.js
    ports:
      - 3001:3001
      - 3002:3002
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  iot-discovery:
    image: disitlab/iot-directory-discover-api:v0
    volumes:
      - ./iot-discovery-conf/:/usr/src/snap4IotServer/snap4cityBroker/conf
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

  iotapp-nr1:
    image: disitlab/snap4city-nodered-v1.1.3-adv:v21
    volumes:
      - ./iotapp-nr1:/data
    ports:
      - "1880:1880"
    depends_on:
      - dashboard-builder
      - keycloak
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  iotapp-nr2:
    image: disitlab/snap4city-nodered-v1.1.3-adv:v21
    volumes:
      - ./iotapp-nr2:/data
    ports:
      - "1881:1880"
    depends_on:
      - dashboard-builder
      - keycloak
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zkdata:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
        - KAFKA_CFG_LISTENERS=CLIENT://:9092
        - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
        - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - kafka:/bitnami/kafka
    depends_on: 
      - zookeeper
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

# IOTOBSF ######################################################
  orionbrokerfilter:
    image: disitlab/orionbrokerfilter:v3.1
    depends_on:
      - orion
    ports:
      - "8443:8443"
    volumes:
      - ./orionbrokerfilter-logs:/usr/local/tomcat/logs/orionbrokerfilter
      - ./orionbrokerfilter-conf:/usr/local/tomcat/credentials
    environment:
      "spring.profiles.active": "deploy"
      "spring.openidconnect.clientid": "orionfilter"
      "spring.openidconnect.username": "userrootadmin"
      "spring.openidconnect.password": "Sl9.wrE@k"
      "spring.openidconnect.token_endpoint": "http://dashboard/auth/realms/master/protocol/openid-connect/token"
      "spring.ownership_endpoint": "http://dashboard/ownership-api/v1/list"
      "spring.delegation_endpoint": "http://dashboard/datamanager/api/v1/apps"
      "spring.orionbroker_endpoint": "http://orion:1026"
      "spring.elapsingcache.minutes": "3"
      "spring.prefixelementID": "Organization:iotobsf"
      "spring.prefix_serviceuri": "http://www.disit.org/km4city/resource/iot"
      "spring.organization": "Organization"
      "spring.context_broker_name": "iotobsf"
      "connection.max": "100"
      "multitenancy": "false"
      "connection.timeout": "10000"
      "JAVA_OPTS": "-DlogFileFolder=/usr/local/tomcat/logs -Dmytruststorepass=password -Dmykeystorepass=password"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  orion:
    image: fiware/orion
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  mongo:
    image: mongo:3.6
    volumes:
      - mongodb:/data/db
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

#KBSSM ################################################################      
  servicemap:
    image: disitlab/servicemap:v3 
#    image: tomcat:9.0.26-jdk8-openjdk-slim
    volumes:
      - ./servicemap-conf:/root/servicemap
      - ./servicemap-iot-conf/logs:/root/iot-log2
      - ./servicemap-iot-conf/:/root/iot-api-config/
      - ./servicemap-conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./servicemap-superservicemap-conf/settings.xml:/usr/local/tomcat/settings.xml
      - ./servicemap-conf/cacerts:/usr/local/openjdk-8/jre/lib/security/cacerts
#    environment:
    ports:
      - 8090:8080
    depends_on:
      - virtuoso-kb
      - dashboarddb
      - keycloak 
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  virtuoso-kb:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./servicemap-conf:/root/servicemap
      - virtuoso:/data
    ports:
      - "8890:8890"      
      - "1111:1111"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
  solr-kb:
    image: solr:6.6.6
    ports:
     - "8983:8983"
    volumes:
      - solr-data:/var/solr    
    command:
      - solr-precreate
      - km4c-index
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

#IOTDES ################################################################      
  nifi:
    image: apache/nifi:1.9.2
    environment:
      NIFI_WEB_HTTP_PORT: 9090
    ports:
      - "9090:9090"
    volumes:
      - ./nifi/extensions:/opt/nifi/nifi-current/extensions
      - ./nifi/conf:/opt/nifi/nifi-current/conf
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
#  elasticsearch:
#    image: elasticsearch:6.8.5
#    #image: elasticsearch:7.9.3
#    #image: amazon/opendistro-for-elasticsearch:1.12.0
#    environment:
#      - 'path.repo=/elastic-bkup'
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"      
#    volumes:
#      - elastic-data:/usr/share/elasticsearch/data
#      - ./elastic-bkup:/elastic-bkup 
#  kibana:
#    image: kibana:6.8.5
#    #image: kibana:7.9.3
#    #image: amazon/opendistro-for-elasticsearch-kibana:1.12.0
#    environment:
#      - 'SERVER_BASEPATH=/kibana'
#      - 'SERVER_REWRITEBASEPATH=true'
##      - 'ELASTICSEARCH_URL=http://elasticsearch:9200'
##      - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
#    ports:
#      - "5601:5601"      

  opensearch-n1:
    image: opensearchproject/opensearch:1.2.3
    environment:
      - discovery.type=single-node
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - network.host=0.0.0.0 
    ports:
      - "9200:9200" 
    depends_on:
      - keycloak
      - ldap-server 
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./opensearch-conf/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./opensearch-conf/node1.pem:/usr/share/opensearch/config/esnode.pem
      - ./opensearch-conf/node1-key.pem:/usr/share/opensearch/config/esnode-key.pem
      - ./opensearch-conf/admin.pem:/usr/share/opensearch/config/admin.pem
      - ./opensearch-conf/admin-key.pem:/usr/share/opensearch/config/admin-key.pem
      - ./opensearch-conf/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./opensearch-conf/security-config.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
      - ./opensearch-conf/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      - ./opensearch-conf/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml
      - ./opensearch-conf/tenants.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/tenants.yml
      - ./opensearch-conf/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml
      - ./opensearch-conf/action_groups.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/action_groups.yml
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.2.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-n1:9200"]' # must be a string with no spaces when specified as an environment variable
      SERVER_BASEPATH: '/kibana'
      SERVER_REWRITEBASEPATH: 'false'
    depends_on:
      - opensearch-n1 
    volumes:
      - ./opensearch-conf/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

######################################################################      
  dashboarddb:
    image: mariadb:10.3
    volumes:
      - dashboarddb:/var/lib/mysql
      - ./mariadb-conf:/etc/mysql/mariadb.conf.d
      - ./database/dashboard.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./database/dashboard-wizard-min.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./database/dashboard-menu.sql:/docker-entrypoint-initdb.d/2_init.sql
      - ./database/dashboard-mobmenu.sql:/docker-entrypoint-initdb.d/3_init.sql
      - ./database/profiledb.sql:/docker-entrypoint-initdb.d/4_init.sql
      - ./database/notificator.sql:/docker-entrypoint-initdb.d/5_init.sql
      - ./database/iot-directory.sql:/docker-entrypoint-initdb.d/6_init.sql
      - ./database/servicemap.sql:/docker-entrypoint-initdb.d/7_init.sql
      - ./database/superservicemap.sql:/docker-entrypoint-initdb.d/8_init.sql
      - ./database/processloader.sql:/docker-entrypoint-initdb.d/9_init.sql
    environment:
      TZ: "Europe/Rome"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'passwordx'
      MYSQL_DATABASE: 'Dashboard'      
    ports:
      - "3306:3306"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

  ldap-server:
    image: disitlab/preconf-openldap:v3 
#    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: "organization"
      LDAP_DOMAIN: "ldap.organization.com"
      LDAP_ADMIN_PASSWORD: "secret"
#    command: [ "--copy-service" ] 
    ports:
      - "389:389"
      - "636:636"
    volumes:
#      - ./ldap-server-conf:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ldap-db:/var/lib/ldap
      - ldap-conf:/etc/ldap/slapd.d
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

  myldap:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap-server"
    ports:
      - "6443:443"
    depends_on:
      - "ldap-server"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"

  keycloak:
    image: disitlab/preconf-keycloak:v4 
#    image: jboss/keycloak:4.8.3.Final 
    command: ["-Djboss.socket.binding.port-offset=8"]
    ports:
      - "8088:8088"
    volumes:
      - keycloak:/opt/jboss/keycloak/standalone/
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin 
    depends_on:
      - ldap-server
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${S4C_LOG_MAX_SIZE:-100m}"
        max-file: "${S4C_LOG_MAX_FILE:-10}"
volumes:
  dashboarddb:
  dashboard-img:
  virtuoso:
  solr-data:
  mongodb:
  elastic-data:
  opensearch-data:
  zkdata:
  kafka:
  keycloak:
  ldap-db:
  ldap-conf:

